/* Generated By:JJTree: Do not edit this line. ASTconstExpressionOrBinaryDef.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTconstExpressionOrBinaryDef extends SimpleNode {
  public ASTconstExpressionOrBinaryDef(int id) {
    super(id);
  }

  public ASTconstExpressionOrBinaryDef(CLang p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CLangVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d0b389f4381ee4d95606d428b997e1c3 (do not edit this line) */
