/* Generated By:JJTree: Do not edit this line. ASTfunctionCall.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTfunctionCall extends SimpleNode {
  public ASTfunctionCall(int id) {
    super(id);
  }

  public ASTfunctionCall(CLang p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CLangVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b54b8b101a5d3f6c6391b151ed098b38 (do not edit this line) */
