/* Generated By:JJTree: Do not edit this line. ASTlistExpressionDef.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTlistExpressionDef extends SimpleNode {
  public ASTlistExpressionDef(int id) {
    super(id);
  }

  public ASTlistExpressionDef(CLang p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CLangVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=28fcd318339093ad6a062fc44ef7df8c (do not edit this line) */
