/* Generated By:JavaCC: Do not edit this line. CLangTreeConstants.java Version 7.0.5 */
public interface CLangTreeConstants
{
  public int JJTIDEXPRESSIONDEF = 0;
  public int JJTCONSTEXPRESSIONDEF = 1;
  public int JJTLISTEXPRESSIONDEF = 2;
  public int JJTFUNCTIONCALL = 3;
  public int JJTUNARYEXPRESSIONDEF = 4;
  public int JJTMULEXPRESSIONDEF = 5;
  public int JJTADDEXPRESSIONDEF = 6;
  public int JJTBINARYBOOLEXPRESSIONCOMPAREDEF = 7;
  public int JJTBINARYEXPRESSIONEQDEF = 8;
  public int JJTBINARYBOOLEXPRESSIONANDDEF = 9;
  public int JJTBINARYBOOLEXPRESSIONORDEF = 10;
  public int JJTBINARYBOOLOPERATORCOMPAREDEF = 11;
  public int JJTBOOLEXPRESSIONDEF = 12;
  public int JJTASSIGNEXPRESSIONDEF = 13;
  public int JJTEXPRESSIONDEF = 14;
  public int JJTVARASSIGNDEFININIT = 15;
  public int JJTLISTVARDEFINEDEF = 16;
  public int JJTVARDEFINEDEF = 17;
  public int JJTSTATEMENTBLOCKDEF = 18;
  public int JJTPARAMDEF = 19;
  public int JJTPARAMLISTDEF = 20;
  public int JJTFUNCTIONDEF = 21;
  public int JJTSOURCECODEDEF = 22;
  public int JJTSTART = 23;
  public int JJTCONSTEXPRESSIONORBINARYDEF = 24;
  public int JJTRETURNSTATEMENTDEF = 25;
  public int JJTWHILESTATEMENTDEF = 26;
  public int JJTFORSTATEMENTDEF = 27;
  public int JJTIFSTATEMENTDEF = 28;
  public int JJTSTATEMENTDEF = 29;


  public String[] jjtNodeName = {
    "idExpressionDef",
    "constExpressionDef",
    "listExpressionDef",
    "functionCall",
    "unaryExpressionDef",
    "mulExpressionDef",
    "addExpressionDef",
    "binaryBoolExpressionCompareDef",
    "binaryExpressionEqDef",
    "binaryBoolExpressionAndDef",
    "binaryBoolExpressionOrDef",
    "binaryBoolOperatorCompareDef",
    "boolExpressionDef",
    "assignExpressionDef",
    "expressionDef",
    "varAssignDefInInit",
    "listVarDefineDef",
    "varDefineDef",
    "StatementBlockDef",
    "paramDef",
    "paramListDef",
    "functionDef",
    "sourceCodeDef",
    "Start",
    "constExpressionOrBinaryDef",
    "ReturnStatementDef",
    "WhileStatementDef",
    "ForStatementDef",
    "IfStatementDef",
    "StatementDef",
  };
}
/* JavaCC - OriginalChecksum=87d62be87daf9d30855a1e20381da9cc (do not edit this line) */
