/* Generated By:JavaCC: Do not edit this line. CLangTreeConstants.java Version 7.0.5 */
public interface CLangTreeConstants
{
  public int JJTCONSTEXPRESSIONDEF = 0;
  public int JJTLISTEXPRESSIONDEF = 1;
  public int JJTFUNCTIONCALL = 2;
  public int JJTUNARYEXPRESSIONDEF = 3;
  public int JJTMULEXPRESSIONDEF = 4;
  public int JJTADDEXPRESSIONDEF = 5;
  public int JJTBINARYBOOLEXPRESSIONCOMPAREDEF = 6;
  public int JJTBINARYEXPRESSIONEQDEF = 7;
  public int JJTBINARYBOOLEXPRESSIONANDDEF = 8;
  public int JJTBINARYBOOLEXPRESSIONORDEF = 9;
  public int JJTBINARYBOOLOPERATORCOMPAREDEF = 10;
  public int JJTBOOLEXPRESSIONDEF = 11;
  public int JJTASSIGNEXPRESSIONDEF = 12;
  public int JJTEXPRESSIONDEF = 13;
  public int JJTVARASSIGNDEFININIT = 14;
  public int JJTVARDEFINEDEF = 15;
  public int JJTSTATEMENTBLOCKDEF = 16;
  public int JJTPARAMDEF = 17;
  public int JJTPARAMLISTDEF = 18;
  public int JJTFUNCTIONDEF = 19;
  public int JJTSOURCECODEDEF = 20;
  public int JJTSTART = 21;
  public int JJTVARASSIGNDEF = 22;
  public int JJTCONSTEXPRESSIONORBINARYDEF = 23;
  public int JJTRETURNSTATEMENTDEF = 24;
  public int JJTWHILESTATEMENTDEF = 25;
  public int JJTFORSTATEMENTDEF = 26;
  public int JJTIFSTATEMENTDEF = 27;
  public int JJTSTATEMENTDEF = 28;


  public String[] jjtNodeName = {
    "constExpressionDef",
    "listExpressionDef",
    "functionCall",
    "unaryExpressionDef",
    "mulExpressionDef",
    "addExpressionDef",
    "binaryBoolExpressionCompareDef",
    "binaryExpressionEqDef",
    "binaryBoolExpressionAndDef",
    "binaryBoolExpressionOrDef",
    "binaryBoolOperatorCompareDef",
    "boolExpressionDef",
    "assignExpressionDef",
    "expressionDef",
    "varAssignDefInInit",
    "varDefineDef",
    "StatementBlockDef",
    "paramDef",
    "paramListDef",
    "functionDef",
    "sourceCodeDef",
    "Start",
    "varAssignDef",
    "constExpressionOrBinaryDef",
    "ReturnStatementDef",
    "WhileStatementDef",
    "ForStatementDef",
    "IfStatementDef",
    "StatementDef",
  };
}
/* JavaCC - OriginalChecksum=504b4e39f91ec2e2b48f57bd48890f57 (do not edit this line) */
